### ISSUE TITLE
Is there any payment module exists?

### ISSUE THREAD

**Issue by programnext** [qor/qor#137]

**Comment by jinzhu** [comment]
not yet, we are going to do that after we release the first public release.

**Comment by programnext** [comment]
Good to hear! Thanks for your guys great work!

**Comment by joeblew99** [comment]
Some thoughts on this. 

There are some terrible providers.  The payment providers hold the money without releasing it for very minor things. This can end up killing the business, because it stops all cash flow. Stripe has done this to a few clients I know in the past.


This one is what I use on all large projects. No business problems at all. Touch wood.

https://www.braintreepayments.com

The golang lib is good I have found :https://github.com/lionelbarrow/braintree-go

**Comment by guycalledseven** [comment]
I have vast (and not enjoyable) experience dealing with a lot of different payment providers and I am about to embark on a project using QOR. 

IMHO focus should be implementing supporting generic enough code / tables in the QOR core that can accomodate different types of providers so that each  provider is isolated enough and can be go tested for implementation. 

Some providers have REST API's, some redirects to them/from them, some return html you have to display + redirect users (3d secure), some expect pingback urls, etc...

**Comment by tonyalaribe** [comment]
I really agree with @guycalledseven. The code should be generic enough, so the developer chooses what payment provider to use.  This would make it more usable for developers in different countries or niches whith their prefered payment providers. I'm still deciding if QOR is a good fit for my next ecommerce project. Would like to contribute to this project in the long run too.

**Comment by jinzhu** [comment]
just fyi, we have stared this a little bit, refer: https://github.com/qor/gomerchant

**Comment by joeblew99** [comment]
Thank you.

Will see if I can help with it

**Comment by MaxHalford** [comment]
Hello,

Is still ongoing? I can't see anything in the documentation.

Best regards, I just discovered QOR and find it amazing, it's just the right balance.

**Comment by jinzhu** [comment]
@MaxHalford we have only defined the API https://github.com/qor/gomerchant/blob/master/gomerchant.go#L6 and developed one payment gateway for now for now... https://github.com/qor/gomerchant/tree/master/gateways/paygent

But we are going to create more when we have time, or you could contribute one based on the API we defined ;)

Thank you.
